### ISSUE TITLE
Попробовать натянуть верстку на Yii2

### ISSUE THREAD

**Issue by seriklav** [SPX-PHP/volosatov-school-yii2#12]
Попробовать натянуть верстку на Yii2
https://www.free-css.com/free-css-templates/page236/sanza

**Comment by splaa** [comment]
предлагаю создать конференцию тема: Обсуждение  вертки

**Comment by seriklav** [comment]
ДА не вопрос )))

**Comment by splaa** [comment]
Предлагаю телеграмм 2.01.2019

**Comment by seriklav** [comment]
Создадим групу по верстке или в личных сообщениях обсудим ???

**Comment by splaa** [comment]
![errorpullrecvesttophpstorm](https://user-images.githubusercontent.com/17740226/50647241-bea18e00-0f80-11e9-95c7-df90ac07def6.png)

**Comment by seriklav** [comment]
Попробуй еще я дал права для pullRequests

**Comment by seriklav** [comment]
НУ как попробовал ???

**Comment by seriklav** [comment]
Ауу ??

**Comment by seriklav** [comment]
Ну как там ???

**Comment by seriklav** [comment]
????
